use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum OverlayAddr {
    V4(std::net::Ipv4Addr),
    V6(std::net::Ipv6Addr),
}

impl OverlayAddr {
    pub fn is_v4(&self) -> bool {
        matches!(self, Self::V4(_))
    }

    pub fn is_v6(&self) -> bool {
        matches!(self, Self::V6(_))
    }
}

impl std::fmt::Display for OverlayAddr {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::V4(addr) => write!(f, "{}", addr),
            Self::V6(addr) => write!(f, "{}", addr),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortRange {
    pub start: u16,
    pub end: u16,
}

impl PortRange {
    pub fn contains(&self, port: u16) -> bool {
        port >= self.start && port <= self.end
    }

    pub fn size(&self) -> u16 {
        self.end - self.start + 1
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CidrRange {
    pub network: OverlayAddr,
    pub prefix_len: u8,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ControllerTlsMode {
    AutoGenerated,
    ExistingCertificate,
    DomainCert,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ControllerConfig {
    pub controller_name: String,
    pub web_port: u16,
    pub node_service_port: u16,
    pub wg_port_range_start: u16,
    pub wg_port_range_end: u16,
    pub public_address: String,
    pub overlay_ipv4_cidr: String,
    pub ipv6_enabled: bool,
    pub tls_mode: ControllerTlsMode,
    pub tls_cert_path: Option<String>,
    pub tls_key_path: Option<String>,
    pub auto_configure_firewall: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentConfig {
    pub node_id: Option<String>,
    pub node_display_name: String,
    pub identity_key_path: String,
    pub wg_private_key_path: String,
    pub parent_address: String,
    pub parent_service_port: u16,
    pub node_service_port: u16,
    pub wg_port_range_start: u16,
    pub wg_port_range_end: u16,
    pub recovery_endpoints: Vec<String>,
}
